version: 2.1
orbs: 
  aws-code-deploy: circleci/aws-code-deploy@1.0.0

workflows: 
  deploy_application_dev: 
    jobs: 
      - 
        aws-code-deploy/deploy: 
			application-name: myApplication
			bundle-bucket: angular-bucket-17
			bundle-key: myS3BucketKey
			deployment-group: myDeploymentGroup1
			service-role-arn: "arn:aws:iam::801391952744:role/CodeDeployServiceRole-new"
			filters: 
				branches: 
				  only: dev
