--- 
orbs: 
  aws-code-deploy: circleci/aws-code-deploy@0.0.10
version: 2.1
workflows: 
  deploy_application: 
    jobs: 
      - 
        aws-code-deploy/deploy: 
          application-name: rbk-tco-backend
          bundle-bucket: tco-app
          bundle-key: tco-backend
          bundle-source: build/
          deployment-group: rbk-tco-backend-dg
          filters: 
            branches: 
              only: dev
          service-role-arn: "arn:aws:iam::688687378425:role/CodeDeployEC2ServiceRole"
      - 
        aws-code-deploy/deploy: 
          application-name: rbk-tco-backend
          bundle-bucket: tco-app
          bundle-key: tco-backend
          bundle-source: build/
          deployment-group: rbk-tco-backend-dg
          filters: 
            branches: 
              only: qa
          service-role-arn: "arn:aws:iam::688687378425:role/CodeDeployEC2ServiceRole"
